name: Production Build

on:
  push:
    branches: [ main ]
    paths:
      - 'src/**'

permissions:
  contents: write

jobs:
  bundle-and-minify:
    name: Bundle & Minify JS
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'
          cache-dependency-path: '.github/workflows/*.yml'

      # - name: Install dependencies
      #   run: npm ci

      - name: Generate Distribution Files
        run: |
          mkdir -p dist
          npx terser src/index.js -o dist/fundle.js --beautify
          npx terser src/index.js -o dist/fundle.min.js --compress --mangle

      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "build: auto-bundle and minify [skip ci]"
          file_pattern: 'dist/*'
          disable_globbing: false
